name: hbm
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  get: ^4.6.1
  intl: ^0.18.1

  get_storage: ^2.0.3
  http: ^1.0.0
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.0.8
  image_picker: ^1.0.0
  path_provider: ^2.0.9
  file_picker: ^5.3.2
  open_file: ^3.2.1
  cached_network_image: ^3.2.0
  connectivity_plus: ^4.0.1
  camera: ^0.10.4
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.2
  app_settings: ^5.0.0
  flutter_svg: ^2.0.5
  flutter_staggered_grid_view: ^0.6.2
  group_button: ^5.1.0
  bottom_navy_bar: ^6.0.0
  pinch_zoom: ^1.0.0
  dropdown_search: ^5.0.3
  file: ^6.1.4
  intro_slider: ^4.2.0
  introduction_screen: ^3.1.7
  expandable_text: ^2.3.0
  infinite_scroll_pagination: ^3.2.0
  country_code_picker: ^3.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  google_maps_flutter: ^2.2.6
  location: ^4.3.0
  flutter_email_sender: ^6.0.1
  mailer: ^6.0.1
  flutter_bkash: ^0.2.0
  dots_indicator: ^3.0.0
  flutter_launcher_icons: ^0.13.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/static/Urbanist-Thin.ttf
        - asset: assets/fonts/static/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/static/Urbanist-Light.ttf
        - asset: assets/fonts/static/Urbanist-Regular.ttf
        - asset: assets/fonts/static/Urbanist-Medium.ttf
        - asset: assets/fonts/static/Urbanist-SemiBold.ttf
        - asset: assets/fonts/static/Urbanist-Bold.ttf
        - asset: assets/fonts/static/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/static/Urbanist-Black.ttf
        - asset: assets/fonts/static/Urbanist-ThinItalic.ttf
        - asset: assets/fonts/static/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/static/Urbanist-LightItalic.ttf
        - asset: assets/fonts/static/Urbanist-Italic.ttf
        - asset: assets/fonts/static/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/static/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/static/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/static/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/static/Urbanist-BlackItalic.ttf

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf

    - family: Acumin
      fonts:
        - asset: assets/fonts/FontsFree-Net-Acumin-Pro-Bold.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
